repos:
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.6
  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo-fmt
        language: system
        pass_filenames: false
        entry: cargo +stable fmt
      - id: circleci-config-validate
        name: circleci-config-validate
        language: system
        files: ^.circleci/config.yml$
        entry: circleci config validate
