dist: xenial
sudo: required

language: python
python:
- '3.6'

cache:
  directories:
    - $HOME/.cargo
    - $HOME/.cache/pip
env:
  global:
    - RUST_VERSION=nightly
    - RUSTCSV_BUILD_DEBUG=False

before_install:
- pip install --upgrade pip
- pip install --upgrade pipenv
- pip install --upgrade twine  # Used by publish scripts
- pipenv install --dev --deploy

install:
- curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain $RUST_VERSION
- export PATH="$HOME/.cargo/bin:$PATH"
- make develop-release

stages:
  - test
  - deploy
  - benchmark

script:
  - make $TARGET # Intentionally unquoted

jobs:
  include:
    - stage: test
      env:
        - TARGET="test test-example-scripts"

    - stage: benchmark
      script: make benchmark-full
      env:
        - TARGET=benchmark-full

      # manylinux cp36
    - stage: deploy
      services:
        - docker
      env:
        - WHEEL_PYTHON_VERSIONS=cp36
          # The wheels should be portable
        - RUSTCSV_BUILD_NATIVE=False
      script: bash travis/deploy.sh
      install: skip
      if: tag IS present

      # manylinux cp37
    - stage: deploy
      services:
        - docker
      env:
        - WHEEL_PYTHON_VERSIONS=cp37
          # The wheels should be portable
        - RUSTCSV_BUILD_NATIVE=False
      script: travis/deploy.sh
      install: skip
      if: tag IS present

    - stage: deploy
      install: skip
      script: make clean build-sdist publish-wheelhouse
      if: tag IS present

# Installing dependencies on travis osx is hell
#       # osx cp36 & cp37
#     - stage: test
#       os: osx
#       language: generic
#       env:
#         - WHEEL_PYTHON_VERSIONS=cp36 cp37
#       script: travis/deploy-osx.sh
#       before_install:
#         # osx only has python 2.7 at the moment
#         # https://github.com/travis-ci/travis-ci/issues/9744
#         - pip install -U pip
#         - pip install -U pipenv
#       install: skip
#       if: tag IS present
