dist: xenial
sudo: required
services:
  - docker

language: python
python:
- '3.6'
cache:
  directories:
    - $HOME/.cargo
env:
- RUST_VERSION=nightly

install:
- pip install pipenv
- pipenv install --dev --deploy
- curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain $RUST_VERSION
- export PATH="$HOME/.cargo/bin:$PATH"
- make develop-release

jobs:
  include:
    - stage: test
      script: make test
    - stage: test
      script: make benchmark-full
    - stage: test
      script: skip
      install: skip
      env:
      - MANYLINUX_PYTHON_VERSIONS=cp36
      - MANYLINUX_PYTHON_VERSIONS=cp37
      deploy:
        - provider: script
          script: bash travis/deploy.sh
          skip_cleanup: true
          on:
            tags: true
