dist: xenial
sudo: required
services:
  - docker

language: python
python:
- '3.6'
cache:
  directories:
    - $HOME/.cargo
env:
  global:
    - RUST_VERSION=nightly

install:
- pip install pipenv
- pipenv install --dev --deploy
- curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain $RUST_VERSION
- export PATH="$HOME/.cargo/bin:$PATH"
- make develop-release

jobs:
  include:
    - stage: test
      script: make test
      env:
        - TARGET=test
    - stage: test
      script: make benchmark-full
      env:
        - TARGET=benchmark-full
    - script: skip
      install: skip
      env:
        - MANYLINUX_PYTHON_VERSIONS=cp36
      if: tag = true
      deploy:
        provider: script
        script: bash travis/deploy.sh
    - script: skip
      install: skip
      env:
        - MANYLINUX_PYTHON_VERSIONS=cp37
      if: tag = true
      deploy:
        provider: script
        script: bash travis/deploy.sh
