dist: xenial
sudo: required

language: python
python:
- '3.6'

cache:
  directories:
    - $HOME/.cargo
env:
  global:
    - RUST_VERSION=nightly

install:
- pip install pipenv
- pipenv install --dev --deploy
- curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain $RUST_VERSION
- export PATH="$HOME/.cargo/bin:$PATH"
- make develop-release

jobs:
  include:
    - stage: test
      script: make test
      env:
        - TARGET=test

    - stage: test
      script: make benchmark-full
      env:
        - TARGET=benchmark-full

    - stage: test
      services:
        - docker
      env:
        - MANYLINUX_PYTHON_VERSIONS=cp36
      script: bash travis/deploy.sh
      install: skip
      if: tag IS present
    - stage: test
      services:
        - docker
      env:
        - MANYLINUX_PYTHON_VERSIONS=cp37
      script: bash travis/deploy.sh
      install: skip
      if: tag IS present
