dist: xenial
sudo: required

language: python
python:
- '3.6'

cache:
  directories:
    - $HOME/.cargo
env:
  global:
    - RUST_VERSION=nightly
    - RUST_EXTENSION_DEBUG=False

before_install:
- pip install pipenv
- pipenv install --dev --deploy

install:
- curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain $RUST_VERSION
- export PATH="$HOME/.cargo/bin:$PATH"
- make develop-release

jobs:
  include:
    - stage: test
      script: make test
      env:
        - TARGET=test

    - stage: test
      script: make benchmark-full
      env:
        - TARGET=benchmark-full

      # manylinux cp36
    - stage: test
      services:
        - docker
      env:
        - MANYLINUX_PYTHON_VERSIONS=cp36
      script: bash travis/deploy.sh
      install: skip
      if: tag IS present

      # manylinux cp37
    - stage: test
      services:
        - docker
      env:
        - MANYLINUX_PYTHON_VERSIONS=cp37
      script: travis/deploy.sh
      install: skip
      if: tag IS present

      # osx cp36 & cp37
    - stage: test
      os: osx
      script: travis/deploy-osx.sh
      install: skip
      if: tag IS present
