dist: xenial
sudo: required
services:
  - docker

language: python
python:
- '3.6'
cache:
- cargo
env:
- RUST_VERSION=nightly

install:
- pip install pipenv
- pipenv install --dev --deploy
- curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain $RUST_VERSION
- export PATH="$HOME/.cargo/bin:$PATH"
- make develop-release

script:
- make test benchmark-full

deploy:
  - provider: script
    script: bash travis/deploy.sh
    skip_cleanup: true

