dist: xenial
sudo: required
services:
  - docker

language: python
python:
- '3.6'
cache:
  directories:
    - $HOME/.cargo
env:
- RUST_VERSION=nightly
- MANYLINUX_PYTHON_VERSIONS=cp36
- MANYLINUX_PYTHON_VERSIONS=cp37

install:
- pip install pipenv
- pipenv install --dev --deploy
- curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain $RUST_VERSION
- export PATH="$HOME/.cargo/bin:$PATH"
- make develop-release

jobs:
  include:
    - stage: test
      script: make test
      env:
        - MANYLINUX_PYTHON_VERSIONS=
    - stage: test
      script: make benchmark-full
      env:
        - MANYLINUX_PYTHON_VERSIONS=
    - stage: test
      script: skip
      install: skip
      if: tag IS present
      deploy:
        - provider: script
          script: bash travis/deploy.sh
