[package]
name = "rust-csv-py"
version = "0.1.0"
authors = ["Joar Wandborg <joar@wandborg.se>"]

[lib]
name = "rustcsv"
crate-type = ["cdylib"]

[dependencies]
csv = "1"
log = "*"
env_logger = "*"
tempfile = "3"

[dependencies.pyo3]
version = "0.4.1"
features = ["extension-module", "python3"]
path = "pyo3"

[build-dependencies]
regex = "1.0.2"
version_check = "0.1.4"

[profile.release]
lto = true
