version: 2.1
jobs:
  test:
    docker:
      - image: circleci/python:3.7
        environment:
          - RUSTCSV_BUILD_RUST_VERSION: nightly-2018-11-03
          - RUSTCSV_BUILD_DEBUG: "False"
    steps:
      - checkout
      - run: git submodule update --init --recursive
      - run: echo 'export PATH=$HOME/.cargo/bin:$PATH' >> "$BASH_ENV"
      - run: pip install --user --upgrade pip pipenv twine
      - run: pipenv install --dev --deploy
      - run: travis/install-rust.sh
      - run: cargo version
      - run: make develop-release
      - run: make test test-example-scripts

workflows:
  version: 2
  test:
    jobs:
      - test: {}
