version: 2.1

executors:
  python:
    docker:
      - image: circleci/python:3.7
        environment:
          - RUSTCSV_RUST_VERSION: nightly-2018-11-03
          - RUSTCSV_BUILD_DEBUG: "False"

commands:
  checkout_recursive:
    description: Check out repository and submodules
    steps:
      - checkout
      - run: git submodule update --init --recursive

  install_rust:
    description: Install rust toochain
    steps:
      - run: echo 'export PATH=$HOME/.cargo/bin:$PATH' >> "$BASH_ENV"
      - run: travis/install-rust.sh
      - run: cargo version

  install_python:
    description: Install python dependencies
    steps:
      - run: pip install --user --upgrade pip pipenv twine
      - run: pipenv install --dev --deploy

jobs:
  # test:
  #   executor: python
  #   steps:
  #     - checkout_recursive
  #     - install_rust
  #     - install_python
  #     - run: make develop-release
  #     - run: make test test-example-scripts

  # benchmark:
  #   executor: python
  #   steps:
  #     - checkout_recursive
  #     - install_rust
  #     - install_python
  #     - run: make develop-release
  #     - run: make benchmark-full

  build-wheel-manylinux:
    parameters:
      python_version:
        type: string
        description: Python runtime identifier(?), e.g. cp37
    executor: python
    steps:
      - checkout_recursive
      - install_python
      - setup_remote_docker
      - run: env WHEEL_PYTHON_VERSIONS='<< parameters.python_version >>' make clean build-wheels-manylinux publish-wheelhouse

workflows:
  version: 2
  test:
    jobs:
      # - test: {}
      - build-wheel-manylinux:
          python_version: cp37
          # requires:
          #   - test
      # - benchmark:
      #     requires:
      #       - test
