version: 2.1

commands:
  recursive:
    description: Check out repository and submodules
    steps:
      - checkout
      - run: git submodule update --init --recursive

  install_rust:
    description: Install rust toochain
    # parameters:
    #   version:
    #     type: string
    #     default: nightly
    steps:
      - run: echo 'export PATH=$HOME/.cargo/bin:$PATH' >> "$BASH_ENV"
      - run: travis/install-rust.sh
      - run: cargo version

jobs:
  test:
    docker:
      - image: circleci/python:3.7
        environment:
          - RUSTCSV_BUILD_RUST_VERSION: nightly-2018-11-03
          - RUSTCSV_BUILD_DEBUG: "False"
    steps:
      - recursive: {}
      - install_rust
      - run: pip install --user --upgrade pip pipenv twine
      - run: pipenv install --dev --deploy
      - run: make develop-release
      - run: make test test-example-scripts


workflows:
  version: 2
  test:
    jobs:
      - test: {}
