version: 2
jobs:
  test:
    docker:
      - image: circleci/python:3.7
        environment:
          - RUSTCSV_BUILD_DEBUG: "False"
    steps:
      - checkout_recursive
      - install_rust
      - run: pip install --user --upgrade pip pipenv twine
      - run: pipenv install --dev --deploy
      - run: make develop-release
      - run: make test test-example-scripts

commands:
  checkout_recursive:
    description: Check out repository and submodules
    steps:
      - checkout
      - run: git submodule update --init --recursive

  install_rust:
    description: Install rust toochain
    parameters:
      version:
        type: string
        default: nightly-2018-11-03
    steps:
      - run: echo 'export PATH=$HOME/.cargo/bin:$PATH' >> "$BASH_ENV"
      - run: echo 'export RUSTCSV_RUST_VERSION=<< parameters.version' >> "$BASH_ENV"
      - run: travis/install-rust.sh
      - run: cargo version


workflows:
  version: 2
  test:
    jobs:
      - test: {}
